version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_MAX_ALLOWED_PACKET=64M
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - mysql-data:/var/lib/mysql
  node_app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=database
    restart: always
volumes:
  mysql-data:
